services:
  proxy:
    build: ./proxy      #todo
    volumes:   #vmtl copy anstatt volume?
      - ../code:/code    #todo
    ports:
      - "8080:80"  #anpassen
  backend:      #gradle + springboot
    build: ./backend    #todo
    volumes:
      - ../backend:/backend #todo
    depends_on:
      - "db"
    environment:         #todo
      POSTGRES_PASSWORD: testpassword12345234jsdbcvu
      POSTGRES_USER: userforpostgres
      POSTGRES_DB: dbforSVQ
  db:       #init skript um eigens schema erweitern
    image: "postgres:latest"
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: testpassword12345234jsdbcvu
      POSTGRES_USER: userforpostgres
      POSTGRES_DB: dbforSVQ
  