services:
  proxy:
    build: ./proxy      #todo
    volumes:
      - ../code:/code    #todo
    ports:
      - "8080:8080"
  backend:
    build: ./backend    #todo
    volumes:
      - ../backend:/backend #todo
    depends_on:
      - "db"
    environment:         #todo
      POSTGRES_PASSWORD: testpassword12345234jsdbcvu
      POSTGRES_USER: userforpostgres
      POSTGRES_DB: dbforSVQ
  db:
    image: "postgres:latest"
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: testpassword12345234jsdbcvu
      POSTGRES_USER: userforpostgres
      POSTGRES_DB: dbforSVQ
  